services:
  db:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bekodb
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

volumes:
  postgres_data:
    # external: true
