version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bekodb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  prisma:
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    environment:
      POSTGRE_SQL_DATABASE_URL: 'postgresql://admin:1234@db:5432/bekodb'
    depends_on:
      - db
    networks:
      - app-network
    entrypoint:
      [
        'sh',
        '-c',
        'npx prisma migrate dev --schema=prisma/postsql.prisma --name init',
      ]

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
