version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_local
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  prisma:
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - default
    entrypoint:
      [
        'sh',
        '-c',
        'npx prisma migrate dev --schema=prisma/postsql.prisma --name init',
      ]

  ngrinder-controller:
    image: ngrinder/controller
    container_name: ngrinder-controller
    restart: always
    ports:
      - '9000:80'
      - '16001:16001'
      - '12000-12009:12000-12009'
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
    networks:
      - app-network

  ngrinder-agent:
    image: ngrinder/agent
    container_name: ngrinder-agent
    restart: always
    depends_on:
      - ngrinder-controller
    networks:
      - app-network
    environment:
      - CONTROLLER_ADDR=ngrinder-controller
    volumes:
      - ./ngrinder-agent:/opt/ngrinder-agent

volumes:
  postgres_data:
  ngrinder-data:

networks:
  app-network:
    driver: bridge
